### ISSUE TITLE
Projeto não executa 

### ISSUE THREAD

**Issue by ClaydsonFernando** [ItaloLR/react-weather#1]
Projeto trava nessa tela com load impossibilitando qualquer outras ação.
<img width="1431" alt="Weather Now 2020-02-03 09-38-45" src="https://user-images.githubusercontent.com/22772156/73653908-24bb8180-4669-11ea-9a9b-6a88f7433670.png">

**Comment by ItaloLR** [comment]
Bom dia Claydson,

Atualizei a documentação com os passos necessários para não ocorrer esse erro. Por favor renomeie o arquivo ".env.example" para somente ".env". Pois o projeto utiliza variáveis de ambiente, sendo uma delas a Key da API.

Agradeço a atenção!
